/*
 * Copyright 2023 dragonfly.ai
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ai.dragonfly.uriel.color.model.rgb

import narr.*
import ai.dragonfly.uriel.*
import ai.dragonfly.uriel.cie.*
import ai.dragonfly.mesh.*
import ai.dragonfly.mesh.shape.*
import slash.*
import slash.matrixf.*
import slash.vectorf.*

import scala.language.implicitConversions

trait RGB { self: WorkingSpace =>

  object RGB extends VectorSpace[3, RGB] {

    opaque type RGB = VecF[3]

    override lazy val usableGamut: Gamut = new Gamut( Cube(1.0, 32).toMeshF )

    override val maxDistanceSquared: Double = 3.0

    def apply(values: NArray[Float]): RGB = dimensionCheck(values, 3).asInstanceOf[RGB]

    /**
     * Factory method to create a fully opaque RGB instance from separate, specified red, green, blue components and
     * a default alpha value of 1.0.
     * Float values that range outside of [0.0-1.0] may give unexpected results.  For values taken from user input, sensors,
     * or otherwise uncertain sources, consider using the factory method in the Color companion object.
     *
     * @see [[ai.dragonfly.color.ColorVectorSpace.RGB]] for a method of constructing RGB objects that validates inputs.
     * @param red   decimal value from [0.0-1.0] representing the red component in RGB space.
     * @param green decimal value from [0.0-1.0] representing the green component in RGB space.
     * @param blue  decimal value from [0.0-1.0] representing the blue component in RGB space.
     * @return an instance of the RGB case class.
     * @example {{{ val c = RGB(72,105,183) }}}
     */
    def apply(red: Float, green: Float, blue: Float): RGB = apply(NArray[Float](red, green, blue))

    /**
     * Factory method to create a fully Opaque RGB color; one with an alpha value of 1.0.
     * Because this method validates each intensity, it sacrifices performance for safety.
     * Although well suited for parsing color data generated by sensors or user input, this method undercuts
     * performance in applications like reading image data.
     *
     * To skip validation and minimize overhead, @see [[ai.dragonfly.color.RGB.apply]]
     *
     * @param red   decimal value from [0.0-1.0] representing the red component in RGB space.
     * @param green decimal value from [0.0-1.0] representing the green component in RGB space.
     * @param blue  decimal value from [0.0-1.0] representing the blue component in RGB space.
     * @return an instance of the RGB class or None if fed invalid input.
     */

    def getIfValid(red: Float, green: Float, blue: Float): Option[RGB] = {
      if (valid0to1(red, green, blue)) Some(apply(red, green, blue))
      else None
    }

    /**
     * Use Color.random() to obtain a random color in the form of an RGB instance.
     * This method executes quickly and without memory costs, but the RGB color space biases toward cool colors.
     * In contrast, the Color.randomFromLabSpace() method takes seconds to initialize and has a memory footprint of several megabytes
     * However, it samples from a perceptually uniform color space and avoids the bias toward cool colors.
     * This method samples the Red, Green, and Blue color components uniformly, but always returns 1.0 for the alpha component.
     *
     * @return a randomly generated color sampled from the RGB Color ColorSpace.
     */
    override def random(r: scala.util.Random = Random.defaultRandom): RGB = VecF[3](r.nextFloat(), r.nextFloat(), r.nextFloat())

    def red(rgb:RGB):Float = rgb(0)
    def green(rgb:RGB):Float = rgb(1)
    def blue(rgb:RGB):Float = rgb(2)

    override def euclideanDistanceSquaredTo(c1: RGB, c2: RGB): Double = c1.euclideanDistanceSquaredTo(c2)

    override def fromVec(v: VecF[3]): RGB = v

//    override def toVec(rgb: RGB): VecF[3] = rgb.asInstanceOf[VecF[3]].copy
//
//    override def toXYZ(rgb: RGB): XYZ = {
//        (M * MatF[3, 1](
//      transferFunction.decode(rgb.red),
//      transferFunction.decode(rgb.green),
//      transferFunction.decode(rgb.blue)
//      )).values.asInstanceOf[XYZ]
//    }

    override def fromXYZ(xyz:XYZ):RGB = xyz.toRGB

    override def toString:String = "RGB"

//    override def vecTo_sRGB_ARGB(v: VecF[3]): ai.dragonfly.mesh.sRGB.ARGB32 = {
//      Gamut.XYZtoARGB32(
//        fromVec(v).toXYZ.asInstanceOf[VecF[3]]
//      ).asInstanceOf[ai.dragonfly.mesh.sRGB.ARGB32]
//    }

    override def fromRGB(rgb: RGB): RGB = rgb.copy

    override def fromRGBA(rgba: RGBA): RGB = RGB(rgba.red, rgba.green, rgba.blue)

    override def fromXYZA(xyza: XYZA): RGB = xyza.toRGB
  }

  type RGB = RGB.RGB

  given VectorColorModel[3, RGB] with {
    extension (rgb: RGB) {

      inline def red: Float = RGB.red(rgb)

      inline def green: Float = RGB.green(rgb)

      inline def blue: Float = RGB.blue(rgb)

      override def render: String = s"RGB($red, $green, $blue)"

      def copy: RGB = RGB(red, green, blue)

      override def similarity(that: RGB): Double = RGB.similarity(rgb, that)

      override def vec: VecF[3] = rgb.asInstanceOf[VecF[3]].copy

      override def toRGB: RGB = RGB(red, green, blue)

      override def toRGBA: RGBA = RGBA(red, green, blue, 1f)

      override def toRGBA(alpha: Float): RGBA = RGBA(red, green, blue, alpha)

      override def toXYZ: XYZ = {
        (M * MatF[3, 1](
          transferFunction.decode(rgb.red),
          transferFunction.decode(rgb.green),
          transferFunction.decode(rgb.blue)
        )).values.asInstanceOf[XYZ]
      }

      override def toXYZA: XYZA = toXYZ.toXYZA

      override def toXYZA(alpha: Float): XYZA = toXYZ.toXYZA(alpha)

    }
  }


  object RGBA extends VectorSpace[4, RGBA] {

    opaque type RGBA = VecF[4]

    override lazy val usableGamut: Gamut = RGB.usableGamut

    override val maxDistanceSquared: Double = 4.0

    def apply(values: NArray[Float]): RGBA = dimensionCheck(values, 4).asInstanceOf[RGBA]

    /**
     * Factory method to create a fully opaque RGB instance from separate, specified red, green, blue components and
     * a default alpha value of 1.0.
     * Float values that range outside of [0.0-1.0] may give unexpected results.  For values taken from user input, sensors,
     * or otherwise uncertain sources, consider using the factory method in the Color companion object.
     *
     * @see [[ai.dragonfly.color.ColorVectorSpace.RGB]] for a method of constructing RGB objects that validates inputs.
     * @param red   decimal value from [0.0-1.0] representing the red component in RGB space.
     * @param green decimal value from [0.0-1.0] representing the green component in RGB space.
     * @param blue  decimal value from [0.0-1.0] representing the blue component in RGB space.
     * @return an instance of the RGB case class.
     * @example {{{ val c = RGB(72,105,183) }}}
     */
    def apply(red: Float, green: Float, blue: Float, alpha: Float): RGBA = apply(NArray[Float](red, green, blue, alpha))

    override def euclideanDistanceSquaredTo(c1: RGBA, c2: RGBA): Double = c1.vec.euclideanDistanceSquaredTo(c2.vec)

    /**
     * Factory method to create a fully Opaque RGB color; one with an alpha value of 1.0.
     * Because this method validates each intensity, it sacrifices performance for safety.
     * Although well suited for parsing color data generated by sensors or user input, this method undercuts
     * performance in applications like reading image data.
     *
     * To skip validation and minimize overhead, @see [[ai.dragonfly.color.RGB.apply]]
     *
     * @param red   decimal value from [0.0-1.0] representing the red component in RGB space.
     * @param green decimal value from [0.0-1.0] representing the green component in RGB space.
     * @param blue  decimal value from [0.0-1.0] representing the blue component in RGB space.
     * @return an instance of the RGB class or None if fed invalid input.
     */

    def getIfValid(red: Float, green: Float, blue: Float, alpha: Float): Option[RGBA] = {
      if (valid0to1(red, green, blue, alpha)) Some(apply(red, green, blue, alpha))
      else None
    }

    /**
     * Use Color.random() to obtain a random color in the form of an RGB instance.
     * This method executes quickly and without memory costs, but the RGB color space biases toward cool colors.
     * In contrast, the Color.randomFromLabSpace() method takes seconds to initialize and has a memory footprint of several megabytes
     * However, it samples from a perceptually uniform color space and avoids the bias toward cool colors.
     * This method samples the Red, Green, and Blue color components uniformly, but always returns 1.0 for the alpha component.
     *
     * @return a randomly generated color sampled from the RGB Color ColorSpace.
     */
    override def random(r: scala.util.Random = Random.defaultRandom): RGBA = VecF[4](r.nextFloat(), r.nextFloat(), r.nextFloat(), r.nextFloat())

    def red(rgb:RGBA):Float = rgb(0)
    def green(rgb:RGBA):Float = rgb(1)
    def blue(rgb:RGBA):Float = rgb(2)
    def alpha(rgb:RGBA):Float = rgb(3)

    override def fromVec(v: VecF[4]): RGBA = v

    override def fromRGB(rgb: RGB): RGBA = RGBA(rgb.red, rgb.green, rgb.blue, 1f)

    override def fromRGBA(rgba: RGBA): RGBA = rgba.copy

    override def fromXYZ(xyz:XYZ):RGBA = fromRGB(xyz.toRGB)

    override def fromXYZA(xyza: XYZA): RGBA = {
      val rgb:RGB = xyza.toRGB
      RGBA(rgb.red, rgb.green, rgb.blue, xyza.alpha)
    }

//    override def vecTo_sRGB_ARGB(v: VecF[4]): ai.dragonfly.mesh.sRGB.ARGB32 = {
//      val c: ai.dragonfly.mesh.sRGB.ARGB32 = Gamut.XYZtoARGB32(
//        fromVec(v).toXYZ.asInstanceOf[VecF[3]]
//      ).asInstanceOf[ai.dragonfly.mesh.sRGB.ARGB32]
//      ai.dragonfly.mesh.sRGB.ARGB32((255 * v(3)).toInt, c.red, c.green, c.blue)
//    }

    override def toString:String = "RGBA"

  }

  type RGBA = RGBA.RGBA

  given VectorColorModel[4, RGBA] with {
    extension (rgba: RGBA) {

      inline def red: Float = RGBA.red(rgba)

      inline def green: Float = RGBA.green(rgba)

      inline def blue: Float = RGBA.blue(rgba)

      inline def alpha: Float = RGBA.alpha(rgba)

      override def render: String = s"RGBA($red, $green, $blue, $alpha)"

      def copy: RGBA = RGBA(red, green, blue, alpha)

      override def similarity(that: RGBA): Double = RGBA.similarity(rgba, that)

      override def vec: VecF[4] = rgba.asInstanceOf[VecF[4]].copy

      override def toRGB: RGB = RGB(red, green, blue)

      override def toRGBA: RGBA = RGBA(red, green, blue, 1f)

      override def toRGBA(alpha:Float): RGBA = RGBA(red, green, blue, alpha)

      override def toXYZ: XYZ = toRGB.toXYZ

      override def toXYZA: XYZA = {
        val xyz: XYZ = toXYZ
        XYZA(xyz.x, xyz.y, xyz.z, rgba.alpha)
      }

      override def toXYZA(alpha:Float): XYZA = {
        val xyz: XYZ = toXYZ
        XYZA(xyz.x, xyz.y, xyz.z, alpha)
      }

    }
  }
}
